### ISSUE TITLE
Code attribution to MolSkill

### ISSUE THREAD

**Issue by josejimenezluna** [schwallergroup/fsscore#1]
Hi @rneeser, many thanks for open-sourcing this!

I've noticed that many of the parts of the repo contain very few modifications from more or less equivalent code available on MolSkill, (e.g. [fsscore scorer](https://github.com/schwallergroup/fsscore/blob/main/src/fsscore/score.py) vs [molskill scorer](https://github.com/microsoft/molskill/blob/main/molskill/scorer.py)).

While MolSkill is MIT-licensed, it would be nice if you added comments in the files/functions/classes that were adapted from or inspired by it. Something like:

```
# adapted from (link from molskill repo)
```

Thanks!

**Comment by rneeser** [comment]
Hi @josejimenezluna!
Thanks for pointing this out! I added the code contribution remarks where it was missing so far. Let me know if you have more questions!
Thanks!
